### ISSUE TITLE
Rocket Launcher for Sale quest

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/VTMB-Unofficial-Patch-by-Wesp#4]
there are two variations of the e-mail based on dependency either
"G.Gary_Photochop == 1 and G.Gary_Damsel == 0 and G.PP == 0"
"G.Gary_Photochop == 1 and G.Gary_Damsel == 0 and G.PP == 1"
but both e-mail are the same and quests are the same... no CD but a wooden toy now.

Wasn't your intention to preserve the CD objective for basic patch?

**Comment by wesp5** [comment]
This is correct in my version from the first 10.1 RC on...

**Comment by miracleflame** [comment]
So sorry you did not utilize Git sooner. Now I could have seen the exact fix diff in a linked commit for this particular issue and which files were involved. Closing this then.
